on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: | 
          docker exec ${{secrets.SERVER_ID}} git stash
          docker exec ${{secrets.SERVER_ID}} git pull
          docker exec ${{secrets.SERVER_ID}} git stash pop
          docker exec ${{secrets.SERVER_ID}} touch .update
          docker restart ${{secrets.SERVER_ID}}
